# Generated by Django 2.2.1 on 2019-06-22 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackerhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
