# Generated by Django 2.2.1 on 2019-06-22 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackerhub', '0002_hackathon_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='date',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='startDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
