# Generated by Django 2.2.1 on 2019-06-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerhub', '0004_auto_20190622_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='eventId',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
