# Generated by Django 2.2.1 on 2019-06-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerhub', '0007_auto_20190622_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
