# Generated by Django 2.2.1 on 2019-06-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerhub', '0008_hackathon_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='logo',
            field=models.ImageField(null=True, upload_to='hackathon_pics'),
        ),
    ]
