# Generated by Django 2.2.1 on 2019-06-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackerhub', '0009_hackathon_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('host', models.CharField(blank=True, default='', max_length=100)),
                ('prize', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='hackathon',
            name='challenges',
            field=models.ManyToManyField(blank=True, to='hackerhub.Challenge'),
        ),
    ]
