# Generated by Django 2.2.1 on 2019-06-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=models.CharField(choices=[('New', 'New hacker'), ('Developer', 'Developer'), ('Business', 'Business'), ('Designer', 'Designer')], default='New', max_length=15),
        ),
    ]
