# Generated by Django 2.2.1 on 2019-06-23 00:40

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190622_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
        migrations.AddField(
            model_name='profile',
            name='skillset',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
