# Generated by Django 2.2.1 on 2019-06-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190623_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='devpost',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.URLField(null=True),
        ),
    ]
